#!/usr/bin/env python3
#
# make_formula.py
# 2026-10-10
# Version: v1.0.0
#
# PURPOSE:
# Writes the Homebrew formula for one release of the Screencap Documentation
# Tool (Formula/screencap-documentation-tool.rb in the
# ILikeHostingServices/homebrew-tap repository). The formula installs the
# Python program with Homebrew's own Python, Tkinter, and FFmpeg, adds the
# screencap and screencap-gui commands, and builds a small
# "Screencap Documentation Tool.app" that can be linked into Applications.
# No Apple Developer account is needed: Homebrew builds the app on the Mac,
# so it is not downloaded and macOS does not quarantine it.
#
# Usage:
#   make_formula.py --version 1.22.0 --out Formula/            (release: hashes the GitHub tag archive)
#   make_formula.py --version 1.22.0 --tarball src.tar.gz --out Formula/   (test: a local archive)

import argparse
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

REPO_URL = "https://github.com/ILikeHostingServices/Screencap-Documentation-Tool"
PYTHON = "3.13"   # Homebrew's python@X.Y and python-tk@X.Y

TEMPLATE = '''# Generated by packaging/homebrew/make_formula.py in
# ILikeHostingServices/Screencap-Documentation-Tool; edit that script, not this file.
class ScreencapDocumentationTool < Formula
  desc "Turns screen recordings into step-by-step screenshot documentation"
  homepage "{repo}"
  url "{url}"
  sha256 "{sha256}"
  license "MIT"

  depends_on "ffmpeg"
  depends_on "python-tk@{py}"
  depends_on "python@{py}"

  def install
    libexec.install Dir["*.py"], "screencap_gui.pyw", "assets", "LICENSE"
    # Tells the program it was installed by Homebrew: its default folders go
    # in ~/Documents and the update check suggests brew upgrade
    (libexec/"package-kind").write "brew\\n"
    python = Formula["python@{py}"].opt_bin/"python{py}"
    {{ "screencap" => "screencap.py", "screencap-gui" => "screencap_gui.pyw" }}.each do |cmd, script|
      (bin/cmd).write <<~EOS
        #!/bin/bash
        exec "#{{python}}" -B "#{{libexec}}/#{{script}}" "$@"
      EOS
      chmod 0755, bin/cmd
    end

    # A small app bundle that starts the GUI, for the Dock and Spotlight
    app = prefix/"Screencap Documentation Tool.app/Contents"
    (app/"MacOS").mkpath
    (app/"Resources").mkpath
    (app/"MacOS/Screencap Documentation Tool").write <<~EOS
      #!/bin/bash
      exec "#{{opt_bin}}/screencap-gui" "$@"
    EOS
    chmod 0755, app/"MacOS/Screencap Documentation Tool"
    iconset = buildpath/"AppIcon.iconset"
    iconset.mkpath
    [16, 32, 128, 256].each do |size|
      system "sips", "-z", size.to_s, size.to_s, "assets/icon.png", "--out", iconset/"icon_#{{size}}x#{{size}}.png"
      system "sips", "-z", (size * 2).to_s, (size * 2).to_s, "assets/icon.png",
             "--out", iconset/"icon_#{{size}}x#{{size}}@2x.png"
    end
    system "iconutil", "-c", "icns", iconset, "-o", app/"Resources/AppIcon.icns"
    (app/"Info.plist").write <<~EOS
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>CFBundleName</key><string>Screencap Documentation Tool</string>
        <key>CFBundleDisplayName</key><string>Screencap Documentation Tool</string>
        <key>CFBundleIdentifier</key><string>io.github.ILikeHostingServices.ScreencapDocumentationTool</string>
        <key>CFBundleVersion</key><string>#{{version}}</string>
        <key>CFBundleShortVersionString</key><string>#{{version}}</string>
        <key>CFBundleExecutable</key><string>Screencap Documentation Tool</string>
        <key>CFBundleIconFile</key><string>AppIcon</string>
        <key>CFBundlePackageType</key><string>APPL</string>
        <key>LSMinimumSystemVersion</key><string>12.0</string>
        <key>NSHighResolutionCapable</key><true/>
      </dict>
      </plist>
    EOS
  end

  def caveats
    <<~EOS
      Start the GUI with:   screencap-gui
      Command line:         screencap --help

      To add the app to Launchpad, Spotlight, and the Dock:
        ln -sf "#{{opt_prefix}}/Screencap Documentation Tool.app" ~/Applications/

      Optional extras:
        brew install tesseract   # blur sensitive text automatically
        brew install pandoc      # Word export
        PDF export uses Google Chrome, Microsoft Edge, or Chromium if installed.

      Recordings and output go in ~/Documents/Screencap Documentation Tool
      by default; any folder can be chosen in the GUI.
    EOS
  end

  test do
    assert_match "v#{{version}}", shell_output("#{{bin}}/screencap --version")
    system Formula["ffmpeg"].opt_bin/"ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
           "-f", "lavfi", "-i", "color=white:s=640x360:r=10:d=8",
           "-vf", "drawbox=x=150:y=100:w=300:h=150:color=gray:t=fill:enable='gte(t,3)'",
           "-c:v", "ffv1", testpath/"src/Demo.mkv"
    system bin/"screencap", "-s", testpath/"src", "-o", testpath/"out"
    assert_path_exists testpath/"out/Demo/steps.md"
    system Formula["python@{py}"].opt_bin/"python{py}", "-c", "import tkinter"
  end
end
'''


def tarball_sha256(version, tarball=None):
    if tarball:
        return hashlib.sha256(Path(tarball).read_bytes()).hexdigest()
    url = f"{REPO_URL}/archive/refs/tags/v{version}.tar.gz"
    with urllib.request.urlopen(url, timeout=60) as response:  # noqa: S310 (fixed GitHub URL)
        return hashlib.sha256(response.read()).hexdigest()


def formula(version, sha256, url=None):
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise SystemExit(f"Version must be X.Y.Z (got {version})")
    url = url or f"{REPO_URL}/archive/refs/tags/v{version}.tar.gz"
    return TEMPLATE.format(repo=REPO_URL, url=url, sha256=sha256, py=PYTHON)


def main(argv=None):
    p = argparse.ArgumentParser(description="Write the Homebrew formula for one release.")
    p.add_argument("--version", required=True, help="Release version, X.Y.Z")
    p.add_argument("--tarball", help="Local source archive (test builds); its file:// URL is used")
    p.add_argument("--out", default="Formula", help="Output folder (default: Formula)")
    args = p.parse_args(argv)
    sha = tarball_sha256(args.version, args.tarball)
    url = Path(args.tarball).resolve().as_uri() if args.tarball else None
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "screencap-documentation-tool.rb"
    path.write_text(formula(args.version, sha, url), encoding="utf-8")
    print(f"Wrote {path} (v{args.version}, sha256 {sha})")


if __name__ == "__main__":
    sys.exit(main())
